apiVersion: v1
kind: Pod
metadata:
  name: lamp-apache-pod
  labels:
    name: myapp-apache
    app: lamp
    type: apache
spec:
  containers:
  - name: lamp-apache-server
    image: rahulraju/lamp-apache
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
