apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  namespace: lamp-app
  selector:
    type: apache
  ports:
  - port: 80
    targetPort: 80
    nodePort: 33333
  type: NodePort
