apiVersion: v1
kind: Pod
metadata:
  name: lamp-apache
  labels:
    name: myapp-apache
    app: lamp
    type: apache
spec:
  containers:
  - name: lamp-apache
    image: my-apache
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
